### ISSUE TITLE
Proposed correction (not true to source text)

### ISSUE THREAD

**Issue by numist** [worrydream/EarlyHistoryOfSmalltalk#32]
["Marion Goldeen"](https://github.com/worrydream/EarlyHistoryOfSmalltalk/blob/3aa6438acc28f38a05004fa058567447881fba51/index.html#L1765-L1766) should have been Marian Goldeen. She wrote about the experience in [The Best of Creative Computing Volume 1 (published 1976, p61)](https://www.atariarchives.org/bcc1/showpage.php?page=61) and currently works at Apple, closing the circle with Kay.

Unfortunately, this typo was present in Kay's original text but it seems reasonable to correct it in this reprinting?

**Comment by worrydream** [comment]
Thank you! Fixed.
